export const videos= [
    {
        id:1,
        nome:'como aumentar sua Geração de leads feat',
        url:'',
        thumb:'',
        type:'Agência',

    },
    {
        id:2,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'ChatBot',   
    },
    {
        id:3,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'ChatBot',   
    },
    {
        id:4,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'ChatBot',   
    },
    {
        id:5,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Marketing',   
    },
    {
        id:6,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Geração',   
    },
    {
        id:7,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Midia',   
    },
    {
        id:8,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Geração',   
    },
    {
        id:9,
        nome:'09',
        url:'',
        thumb:'',
        type:'Midia',   
    },
    {
        id:10,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:11,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:12,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:13,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:14,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:15,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:16,
        nome:'16',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:17,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:18,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:19,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:20,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:21,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:22,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:23,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:24,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:25,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:26,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:27,
        nome:'27',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:28,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:29,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:30,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:31,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:32,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:33,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:34,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:35,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:36,
        nome:'36',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:37,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:38,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:39,
        nome:'como aumentar sua Geração de leads feat. Traktor',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    {
        id:40,
        nome:'40',
        url:'',
        thumb:'',
        type:'Agência',   
    },{
        id:41,
        nome:'sadsafsadsadsa',
        url:'',
        thumb:'',
        type:'Agência',   
    },
    
    
]